### ISSUE TITLE
Pop Mirror Not Syncing?

### ISSUE THREAD

**Issue by pbui** [pop-os/repo-ubuntu-mirror#3]
After https://github.com/pop-os/repo-ubuntu-mirror/commit/37c47207233c1a9d6f6c55c028e3fd8c14350c33, it appears that https://apt.pop-os.org has stopped updating (rather syncing with the Ubuntu mirror).

Looking at http://apt.pop-os.org/ubuntu/dists/jammy/main/binary-amd64/, the `Packages` file has not updated since `19-Sep-2022` which is about the time that change went into effect.

Looking at the equivalent http://us.archive.ubuntu.com/ubuntu/ubuntu/dists/jammy/main/binary-amd64/ and http://mirror.math.princeton.edu/pub/ubuntu/dists/jammy/main/binary-amd64/, it appears that those directories match each other, but are not mirrored to the pop server... suggesting perhaps the new script is not running or is not completing.

In fact the hierarchy of the apt.pop-os.org server does not match either the ubuntu or princeton mirrors, which is strange if rsync is working properly.

I only noticed that the pop apt mirror was not getting ubuntu updates because my Ubuntu 22.04 servers recently got a new python3.10 package (https://packages.ubuntu.com/jammy-updates/python3.10) but my pop clients did not get this update (they usually get the same updates).

**Comment by mmstick** [comment]
The server is in the process of being upgraded, and the sync issues resolved.

**Comment by jackpot51** [comment]
We are building a full mirror using rsync at https://apt-origin.pop-os.org/ubuntu-test/ that will replace https://apt-origin.pop-os.org/ubuntu/. I hope to switch it over soon. This resolves syncing issues that sometimes happen and also provides other series than 22.04 on the Pop mirror.

**Comment by jackpot51** [comment]
We have performed this switch, please give it a try now. We sync with the Ubuntu repo about every hour.

**Comment by pbui** [comment]
It works now, thank you.
